let myDeck = [
"Plains (LTR)",
"Meticulous Archive (MKM)",
"The Celestus (MID)",
"The Wandering Emperor (NEO)",
"Jace, the Perfected Mind (ONE)",
"Temporary Lockdown (DMU)",
"Faithful Mending (MID)",
"Sunfall (MOM)",
"Tezzeret, Betrayer of Flesh (NEO)",
"Teferi, Who Slows the Sunset (MID)",
"Restless Fortress (WOE)",
"Farewell (NEO)",
"Copperline Gorge (ONE)",
"Memory Deluge (MID)",
"Invasion of New Phyrexia (MOM)",
"Depopulate (SNC)",
"Conduit of Worlds (ONE)",
"Caves of Koilos (DMU)",
"Darkslick Shores (ONE)",
"Razorverge Thicket (ONE)",
"Yavimaya Coast (DMU)",
"Breach the Multiverse (MOM)",
"Gix's Command (BRO)",
"Llanowar Wastes (BRO)",
"Rockfall Vale (MID)",
"Crystal Grotto (WOE)",
"Teferi, Temporal Pilgrim (BRO)",
"Edgewall Inn (WOE)",
"Repair and Recharge (BRO)",
"Collector's Vault (WOE)",
"Invasion of Tolvada (MOM)",
"Kaya, Intangible Slayer (ONE)",
"Invasion of Arcavios (MOM)",
"Scene of the Crime (MKM)",
"Scoured Barrens (NEO)",
"Chrome Host Seedshark (MOM)",
"Spirit-Sister's Call (NEO)",
"Public Thoroughfare (MKM)",
"Wrenn and Seven (MID)",
"Matzalantli, the Great Door (LCI)",
"Virtue of Persistence (WOE)",
"Pit of Offerings (LCI)",
"Werefox Bodyguard (WOE)",
"Sokenzan, Crucible of Defiance (NEO)",
"Wooded Ridgeline (DMU)",
"Island (WOE)",
"Mountain (DAR)",
"Realmbreaker, the Invasion Tree (MOM)",
"Thornwood Falls (MOM)",
"Hidden Courtyard (LCI)",
"Swamp (DAR)",
"Shivan Reef (DMU)",
"Sulfurous Springs (DMU)",
"Battlefield Forge (BRO)",
"Chimil, the Inner Sun (LCI)",
"Rite of Oblivion (MID)",
"Hidden Volcano (LCI)",
"Cankerbloom (ONE)",
"Echoing Deeps (LCI)",
"Rocco, Cabaretti Caterer (SNC)",
"Etali, Primal Conqueror (MOM)",
"Titania's Command (BRO)",
"Hidden Cataract (LCI)",
"Skyfisher Spider (BRO)",
"Sheoldred (MOM)",
"Lukka, Bound to Ruin (ONE)",
"Brass's Tunnel-Grinder (LCI)",
"Vohar, Vodalian Desecrator (DMU)",
"Invasion of Innistrad (MOM)",
"Portal to Phyrexia (BRO)",
"Old Rutstein (VOW)",
"Case of the Uneaten Feast (MKM)",
"Glissa Sunslayer (ONE)",
"Thalia and The Gitrog Monster (MOM)",
"The Eternal Wanderer (ONE)",
"Restless Anchorage (LCI)",
"Stensia Uprising (VOW)",
"Hulking Metamorph (BRO)",
"Swiftwater Cliffs (MOM)",
"Brokers Ascendancy (SNC)",
"Terror Tide (LCI)",
"Squirming Emergence (LCI)",
"Volatile Fault (LCI)",
"Vivien on the Hunt (SNC)",
"The Enigma Jewel (LCI)",
"Urabrask's Forge (ONE)",
"Threefold Thunderhulk (LCI)",
"The Everflowing Well (LCI)",
"One with the Multiverse (BRO)",
"Visions of Phyrexia (BRO)",
"Blast Zone (BRO)",
"Cavernous Maw (LCI)",
"Forgotten Monument (LCI)",
"Mirrex (ONE)",
"Sunken Citadel (LCI)",
"Hidden Nursery (LCI)",
"Captivating Cave (LCI)",
"Argoth, Sanctum of Nature (BRO)",
"Hidden Necropolis (LCI)",
"Agatha's Soul Cauldron (WOE)",
"Restless Prairie (LCI)",
"Stimulus Package (SNC)",
"Treasure Map (LCI)",
"Underground Mortuary (MKM)",
"Fortified Beachhead (BRO)",
"Angel of Suffering (SNC)",
"Reckless Handling (MAT)",
"The Mycosynth Gardens (ONE)",
"Hall of Tagsin (BRO)",
"Restless Cottage (WOE)",
"Into the Fire (MOM)",
"Illicit Shipment (SNC)",
"The Temporal Anchor (BRO)",
"Liliana of the Veil (DMU)",
"Virtue of Knowledge (WOE)",
"Jin-Gitaxias, Progress Tyrant (NEO)",
"Cosmium Confluence (LCI)",
"Crawling Infestation (VOW)",
"Timeless Lotus (DMU)",
"Invasion of New Capenna (MOM)",
"Tocasia, Dig Site Mentor (BRO)",
"Nahiri's Resolve (MAT)",
"Cut Your Losses (SNC)",
"Chandra, Hope's Beacon (MOM)",
"Glorious Sunrise (VOW)",
"Karn's Sylex (DMU)",
"Third Path Iconoclast (BRO)",
"Mondrak, Glory Dominus (ONE)",
"Sunset Revelry (MID)",
"Monastery Mentor (MOM)",
"Skyswimmer Koi (NEO)",
"Dollhouse of Horrors (VOW)",
"Wrenn and Realmbreaker (MOM)",
"Diregraf Rebirth (MID)",
"Atraxa, Grand Unifier (ONE)",
"Vorinclex (MOM)",
"Lush Portico (MKM)",
"Tangled Islet (DMU)",
"Buried in the Garden (MKM)",
"Invasion of Segovia (MOM)",
"Dryad's Revival (MID)",
"Eruth, Tormented Prophet (VOW)",
"Skybridge Towers (SNC)",
"Network Terminal (NEO)",
"Waterfront District (SNC)",
"Tramway Station (SNC)",
"Tamiyo, Compleated Sage (NEO)",
"Dockside Chef (NEO)",
"Racers' Ring (SNC)",
"Botanical Plaza (SNC)",
"Analyze the Pollen (MKM)",
"Aftermath Analyst (MKM)",
"Shigeki, Jukai Visionary (NEO)",
"Branch of Vitu-Ghazi (MKM)",
"Insidious Roots (MKM)",
"Persistent Specimen (VOW)",
"Roaring Earth (NEO)",
"Coati Scavenger (LCI)",
"Maestros Ascendancy (SNC)",
"Plargg and Nassari (MAT)",
"Doppelgang (MKM)",
"Soul of Windgrace (DMU)",
"Expand the Sphere (ONE)",
"Tarrian's Journal (LCI)",
"Invasion of Zendikar (MOM)",
"Vraska's Fall (ONE)",
"Invasion of Amonkhet (MOM)",
"Ichormoon Gauntlet (ONE)",
"Staff of Compleation (ONE)",
"Invasion of Kaldheim (MOM)",
"Case of the Locked Hothouse (MKM)",
"Flotsam // Jetsam (MKM)",
"Tough Cookie (WOE)",
"Tameshi, Reality Architect (NEO)",
"Tatyova, Steward of Tides (DMU)",
"Drannith Ruins (MAT)",
"Glittering Stockpile (SNC)",
"Forest (M21)",
"Oni-Cult Anvil (NEO)",
"Meticulous Excavation (BRO)",
"Invasion of Fiora (MOM)",
"Blossoming Sands (MOM)",
"Evolving Door (SNC)",
"No Witnesses (MKM)",
"Arcane Bombardment (SNC)",
]